// backend/src/domain/admin/value-objects/ReportReason.ts
export enum ReportReason {
  INCORRECT_INGREDIENTS = 'INCORRECT_INGREDIENTS',
  MISSING_ALLERGEN = 'MISSING_ALLERGEN',
  WRONG_CROSS_CONTAMINATION = 'WRONG_CROSS_CONTAMINATION',
  CLIENT_REFUSED_PAYMENT = 'CLIENT_REFUSED_PAYMENT',
  CLIENT_ABSENT = 'CLIENT_ABSENT',
  FRAUDULENT_ORDER = 'FRAUDULENT_ORDER',
  OTHER = 'OTHER',
}
